version: '3'
services:
  mds:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    links:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=mds
    command: poetry run uvicorn mds.app:app --reload
  db:
    image: postgres
    environment:
      - POSTGRES_USER=mds
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
